version: '3.8'

services:
  db:
    image: postgres:15
    container_name: projectdream-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dream_user
      POSTGRES_PASSWORD: dream_pass
      POSTGRES_DB: dream_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
